name: BukkitApi
version: '${project.version}'
main: org.BukkitApi.main.GameApi
authors: [ OyunTarayici ]
commands:
  bukkitapi:
    usage: /<command>
    description: Bukkit api example
    aliases:
      - btapi
