name: BukkitApi
version: '1.0-SNAPSHOT'
main: org.BukkitApi.main.GameApi
authors: [ OyunTarayici ]
commands:
  bukkitapi:
    usage: /<command>
    description: Bukkit api example
    aliases:
      - btapi
